### ISSUE TITLE
css page

### ISSUE THREAD

**Issue by blekmus** [fire-walker/docs#45]
https://css-tricks.com/keyboard-only-focus-styles/

**Comment by blekmus** [comment]
```css
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;

    /* get rid of the miserable chrome blue border highlight */
    -webkit-tap-highlight-color: transparent;

    /* disable text highlight */
    /* user-select: none; */
}


*:focus {
    outline: none;
}

```

**Comment by blekmus** [comment]
```css
@font-face {
    font-family: 'Bebas Neue';
    src: url('../fonts/BebasNeue-Regular.ttf');
    font-weight: 400;
    font-style: normal;
}

@font-face {
    font-family: 'Source Sans Pro';
    src: url('../fonts/SourceSansPro-BlackItalic.ttf');
    font-weight: 900;
    font-style: italic;
}
```
